repositoryUrl: https://github.com/picocom-ng/picocom
branches:
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - - '@codedependant/semantic-release-docker'
    - dockerRegistry: ghcr.io
      dockerProject: picocom-ng
      dockerImage: picocom
      dockerTags: ['latest', '{{version}}', '{{major}}', '{{major}}.{{minor}}'],
      dockerFile: Containerfile
  - - '@semantic-release/exec'
    - prepareCmd: bash ci/make-release-tarball.sh ${nextRelease.version}
  - - '@semantic-release/github'
    - assets:
        - path: release/*
